### PR TITLE
Changed the Parse<T> method to return T? instead of Either<T, Failure>

### PR DESCRIPTION
**Pull request by H4xX0r1337**

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
Did you run the tests?

**Comment by H4xX0r1337** [comment]
The test project is broken on my computer, i couldn't run them.

**Comment by WhiteBlackGoose** [comment]
@H4xX0r1337 I added the tests to the main branch. Could you rebase main on your branch? OR you can just simply copy that yml file from .github/workflows from main branch to yours and push to PR. It will test it all automatically

**Comment by WhiteBlackGoose** [comment]
@H4xX0r1337 thanks for your contribution!

**Pull request merged**
